apiVersion: v1
kind: ConfigMap
metadata:
  name: miniflux-config
data:
  POSTGRES_USER: manosriram
  POSTGRES_DB: minifluxrss
  RUN_MIGRATIONS: "1"
  CREATE_ADMIN: "1"
  ADMIN_USERNAME: manosriram
  DEBUG: "1"
